c;

diff --git a/setenv b/setenv
--- a/setenv
+++ b/setenv
@@ -22,6 +22,14 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 
-cd "veins" && . ./setenv; cd - > /dev/null
-cd "iov_sim" && . ./setenv; cd - > /dev/null
+# Check if called from IoV Federated Learning directory
+test -f print-iov_sim-version >/dev/null 2>&1
+if [ "$?" -ne 0 ]; then
+	echo 'Error: current working directory does not look like a IoV Federated Learning root directory. Aborting.' >&2
+	return 1
+fi
+
+# Add Veins directory to PATH
+IOV_SIM_DIR="$(pwd)"
+export PATH="$PATH":"$IOV_SIM_DIR/bin"
 
